# Blog settings
permalink: /blog/:title


# My variables
name: Adil ÖZTAŞER
description: Özgür yazılımcı.
tags: adil,adil öztaşer,öztaşer,django,gnu/linux,özgür yazılım


# Sass
sass:
  style: :compressed
  sass_dir: _sass


# Markdown
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
highlighter: rouge
