# General Jekyll Config
permalink: /:title/
paginate_path: /page/:num/
highlighter: rouge
lsi: false
gems:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-gist

gist:
  noscript: false

exclude: [LICENSE, CNAME, README.md, .gitignore, Gemfile, Gemfile.lock]
timezone: 'Europe/Istanbul'
encoding: 'utf-8'

# Setup
title:            Adil ÖZTAŞER
tagline:          Blog
description:      ""
url:              http://oztaser.com

author:
  name:           'Adil ÖZTAŞER'
  url:            'http://oztaser.com'
  email:          'a@oztaser.com'
  twitter:	      'http://twitter.com/adiloztaser'
